name: Blue/Green deployment test

on:
  push:
    branches:
    - develop

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  IMAGE: canary
  REGISTRY: asia.gcr.io
  GKE_CLUSTER: devops-sandbox
  GKE_ZONE: asia-east2-b

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Set env variables for develop
      if: ${{ contains(github.ref, 'develop') }}
      run: |-
        echo "::set-env name=CONFIG_PATH::.kubernetes/overlays/dev"
        echo "::set-env name=NAMESPACE::dev"
        echo "::set-env name=VERSION::$GITHUB_SHA"
        echo "::set-env name=PHASE::DEVELOPMENT"
    
    - name: Checkout
      uses: actions/checkout@v2
  
    - name: Setup gcloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: "290.0.1"
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Docker build
      run: |-
        gcloud --quiet auth configure-docker
        docker build -t "$REGISTRY/$PROJECT_ID/$IMAGE:$VERSION" .
        docker push "$REGISTRY/$PROJECT_ID/$IMAGE:$VERSION"

    - name: Kubernetes deploy
      run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

        cd "./$CONFIG_PATH"

        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize
        ./kustomize edit set namespace "$NAMESPACE"
        ./kustomize edit set add configmap version-cm --from-literal=VERSION="$VERSION"
        ./kustomize edit set image MUSEROOM_IMAGE:TAG="$REGISTRY/$PROJECT_ID/$IMAGE:$VERSION"
        ./kustomize build . | kubectl apply -f -